const userActionTypes = {
    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    USER_LOGOUT: "USER_LOGOUT",
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
    DETAILS_UPDATE_REQUEST: "DETAILS_UPDATE_REQUEST",
    DETAILS_UPDATE_FAIL: "DETAILS_UPDATE_FAIL",
    DETAILS_UPDATE_SUCCESS: "DETAILS_UPDATE_SUCCESS"
}

export default userActionTypes;